server:
  port: 8080

spring:
  config:
    import:
      - storage-rdb.yml

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka